rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_script:
  - "psql -c 'create role postgres SUPERUSER LOGIN;' postgres"
  - "psql -c 'create database catarse_test;' -U postgres postgres"

script:
  - "bundle exec rspec spec"

branches:
  only:
    - master
